name: CI

on:
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Maven settings
        run: |
          # 检查 Secret 是否为空
          if [ -z "${{ secrets.MAVEN_SETTINGS_BASE64 }}" ]; then
            echo "Using default Maven settings"
            mkdir -p $HOME/.m2
            cat > $HOME/.m2/settings.xml <<EOF
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                          https://maven.apache.org/xsd/settings-1.0.0.xsd">
              <mirrors>
                <mirror>
                  <id>central</id>
                  <name>Central Repository</name>
                  <url>https://repo.maven.apache.org/maven2</url>
                  <mirrorOf>central</mirrorOf>
                </mirror>
              </mirrors>
            </settings>
            EOF
          else
            echo "Creating settings.xml from secret"
            mkdir -p $HOME/.m2
            echo "${{ secrets.MAVEN_SETTINGS_BASE64 }}" | base64 --decode > $HOME/.m2/settings.xml
          fi

      - name: Build with Maven
        run: mvn --batch-mode clean install

      - name: Find built JAR
        id: find-jar
        run: |
          JAR_PATH=$(find target -name '*.jar' | grep -v 'original' | head -n 1)
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: Ip2region Artifacts
          path: ${{ env.JAR_PATH }}
